language: python
python:
    - "2.6"
    - "2.7"
env:
    - DJANGO=1.6.0
    - DJANGO=1.5.5
    - DJANGO=1.4.10
virtualenv:
    system_site_packages: true
install:
    - pip install -q coveralls Django==$DJANGO --use-mirrors
    - pip install -r requirements.txt
services:
    - memcached
    - redis-server
before_script:
    - psql -c 'create database varifydb;' -U postgres
script:
    - coverage run test_suite.py
after_success:
    - coveralls
